spring.application.name=ProjectMedSave

server.port=8080
#spring.datasource.url=jdbc:h2:mem:blog_database
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=masterkey
#spring.sql.init.schema-locations=classpath*:schema.sql
#spring.sql.init.data-locations=classpath*:data.sql
#spring.sql.init.mode=always
#
## H2 Database Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/console
#spring.h2.console.settings.trace=true
#spring.h2.console.settings.web-allow-others=true

# --- DATABASE CONFIGURATION (ORACLE) ---
# =======================================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never

#// --- DATABASE CONFIGURATION (Wallet Autonomous) ---
#spring.datasource.url=jdbc:oracle:thin:@medsaveadb_tp?TNS_ADMIN=C:/Users/pedro/OneDrive/Documentos/Challenge/Oracle-Java-Advanced/ProjectMedSave/Wallet_medsaveadb
#spring.datasource.username=WKSP_WKSPMEDSAVEAPP
#spring.datasource.password=MedSave1@Fiap!
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true